apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook-container
        image: xldevdocker/guestbook:92694bd
        env:
        - name: REDIS_HOST
          value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: ClusterIP
  ports:
  - name: guestbook
    port: 8080
  selector:
    app: guestbook
